"""init

Revision ID: e1012f3b10e6
Revises: 
Create Date: 2026-05-14 11:56:54.061876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1012f3b10e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('actor_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_name', sa.String(length=255), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('birth_place', sa.String(length=255), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('gender', sa.Enum('M', 'K', name='gender'), nullable=True),
    sa.PrimaryKeyConstraint('actor_id')
    )
    with op.batch_alter_table('actors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actors_actor_name'), ['actor_name'], unique=True)

    op.create_table('directors',
    sa.Column('director_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('director_name', sa.String(length=100), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('birth_place', sa.String(length=255), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('gender', sa.Enum('M', 'K', name='gender'), nullable=True),
    sa.PrimaryKeyConstraint('director_id')
    )
    with op.batch_alter_table('directors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_directors_director_name'), ['director_name'], unique=True)

    op.create_table('genres',
    sa.Column('genre_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('genre_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('genre_id'),
    sa.UniqueConstraint('genre_name')
    )
    op.create_table('movies',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('original_language', sa.String(length=50), nullable=True),
    sa.Column('poster_url', sa.String(length=500), nullable=True),
    sa.Column('trailer_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('movie_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('movie_actors',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('movie_role', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.actor_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.movie_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id', 'actor_id')
    )
    with op.batch_alter_table('movie_actors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movie_actors_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movie_actors_movie_id'), ['movie_id'], unique=False)

    op.create_table('movie_directors',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('director_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['director_id'], ['directors.director_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.movie_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id', 'director_id')
    )
    with op.batch_alter_table('movie_directors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movie_directors_director_id'), ['director_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movie_directors_movie_id'), ['movie_id'], unique=False)

    op.create_table('movies_genres',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.genre_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.movie_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id', 'genre_id')
    )
    with op.batch_alter_table('movies_genres', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movies_genres_genre_id'), ['genre_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movies_genres_movie_id'), ['movie_id'], unique=False)

    op.create_table('rentals',
    sa.Column('rental_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('rental_date', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.movie_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('rental_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rentals')
    with op.batch_alter_table('movies_genres', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movies_genres_movie_id'))
        batch_op.drop_index(batch_op.f('ix_movies_genres_genre_id'))

    op.drop_table('movies_genres')
    with op.batch_alter_table('movie_directors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movie_directors_movie_id'))
        batch_op.drop_index(batch_op.f('ix_movie_directors_director_id'))

    op.drop_table('movie_directors')
    with op.batch_alter_table('movie_actors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movie_actors_movie_id'))
        batch_op.drop_index(batch_op.f('ix_movie_actors_actor_id'))

    op.drop_table('movie_actors')
    op.drop_table('users')
    op.drop_table('movies')
    op.drop_table('genres')
    with op.batch_alter_table('directors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_directors_director_name'))

    op.drop_table('directors')
    with op.batch_alter_table('actors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actors_actor_name'))

    op.drop_table('actors')
    # ### end Alembic commands ###
